### ISSUE TITLE
failed to fetch digest: 404 Not Found 

### ISSUE THREAD

**Issue by ahelal** [dpb587/github-status-resource#1]
Hey thank you for repo. I am trying to use the github status

i get the following error 

```
resource script '/opt/resource/check []' failed: exit status 1
stderr:
failed to fetch digest: 404 Not Found
```

my config

``` yaml
resource_types    :
  - name          : "github-status"
    type          : docker-image
    source        : 
      repository  : dpb587/github-status-resource
      tags        : master
resources         :
  - name          : status
    type          : github-status
    source        :
      repository  : myrepo/myproj
      access_token: {{github_token}}
jobs:
  - name   : PR-initial-tests
    plan   :
#       ..... other stuf
      - put: status
        params: {commit: automation-artifcat/commitish, state: success, description: Drafting release }
```

Any pointers what i am doing wrong ?
